### ISSUE TITLE
yarn install - 401 Unauthorized

### ISSUE THREAD

**Issue by vilder** [Stremio/stremio-web#172]
yarn install
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://npm.pkg.github.com/download/@stremio/stremio-core-web/0.12.0/e498bcdf44176c46602f06a97cfb76c2e05ac15bd9f42058f10fab17fe8399da: Request failed \"401 Unauthorized\"".

**Comment by sleeyax** [comment]
You get that error when you didn't [configure yarn to work Github Packages](https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-npm-for-use-with-github-packages), as stated in the README. 

For more info see [this PR](https://github.com/Stremio/stremio-web/pull/165).

**Comment by vilder** [comment]
Thanks , this solved it

**Comment by Ivshti** [comment]
related #166
