### ISSUE TITLE
External links for torrent addons

### ISSUE THREAD

**Issue by jaruba** [Stremio/stremio-web#177]
Torrent addons should be supported also, while streaming would be possible while the streaming server is available, when it is not available it should be handled as an external URL to a magnet link: `"magnet:?xt=urn:btih:" + stream.infoHash`

The trackers should also be added to the magnet link if `(stream.sources || []).length` is truthy.

This could be added as an "Open External" button in the message that the streaming server is not available when pressing torrent stream results. A "Remember choice" option might also be helpful.

**Comment by nklhtv** [comment]
Done
