### ISSUE TITLE
yarn install - 404

### ISSUE THREAD

**Issue by citkane** [Stremio/stremio-web#180]
As per https://github.com/Stremio/stremio-web/issues/172, I have configured .npmrc to:

```bash
@stremio:registry=https://npm.pkg.github.com
//npm.pkg.github.com/:_authToken=...mytoken
```
and ```yarn install```, but my error message has gone from ```401``` to:
```bash
error An unexpected error occurred: "https://npm.pkg.github.com/download/@stremio/stremio-core-web/0.12.0/e498bcdf44176c46602f06a97cfb76c2e05ac15bd9f42058f10fab17fe8399da: Request failed \"404 Not Found\"".
```
I checked the url from a browser, and my token gets me logged in, but response is:
```json
{"error":"Version \"0.12.0\" does not exist on NPM package \"stremio-core-web\" under owner \"stremio\""}
```
I tried ```npm install```, but get:
```bash
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for @stremio/stremio-core-web
```
It would appear that install is broken both ways.
[yarn-error.log](https://github.com/Stremio/stremio-web/files/4740034/yarn-error.log)
[2020-06-06T12_44_06_355Z-debug.log](https://github.com/Stremio/stremio-web/files/4740036/2020-06-06T12_44_06_355Z-debug.log)

**Comment by rodrigotm** [comment]
+1

**Comment by aunetx** [comment]
Same for me

**Comment by mayconbenito** [comment]
I added `org:` before the organization name and it worked [Search for Github Packages!](https://help.github.com/pt/github/searching-for-information-on-github/searching-for-packages#about-searching-for-packages)

My .npmrc
```
org:@stremio:registry=https://npm.pkg.github.com
//npm.pkg.github.com/:_authToken=GITHUB_ACCESS_PERSONAL_TOKEN
```

**Comment by rodrigotm** [comment]
@mayconbenito My case:

With ```org:``` = Request failed \"401 Unauthorized\""
Without ```org:``` = Request failed \"404 Not Found\""

My .npmrc

```
@stremio:registry=https://npm.pkg.github.com
//npm.pkg.github.com/:_authToken=XXXXXXXXX...
```
404

```
org:@stremio:registry=https://npm.pkg.github.com
//npm.pkg.github.com/:_authToken=XXXXXXXXX...
```
401

**Comment by mayconbenito** [comment]
@rodrigotm 

I think they removed the version 0.12.0 of @stremio/stremio-core-web but if you change the version to 0.13.0 on the package.json it should work.

[Here](https://npm.pkg.github.com/download/@stremio/stremio-core-web/) you can see the available versions of @stremio/stremio-core-web

**Comment by nklhtv** [comment]
We decided to migrate to NPM to avoid the need of configuring Github packages. You can checkout the lastest development branch.

**Comment by xjsonx** [comment]
hello, i have a error "Not Found - GET https://npm.pkg.github.com/@stremio%2fstremio-video - npm package "stremio-video" does not exist under owner "stremio"" when use npm install

**Comment by nklhtv** [comment]
I think now you have to delete the GitHub Packages configuration in .npmrc
