### ISSUE TITLE
video list is empty in meta details. Dev env

### ISSUE THREAD

**Issue by madan81k** [Stremio/stremio-web#189]
cloned the latest dev env and trying to run locally. but when going to the metadetails of any movie, the video list comes as empty. this below api doesnt have any videos. its empty.
https://v3-cinemeta.strem.io/meta/movie/tt7975244.json

**Comment by nklhtv** [comment]
Cinemeta addon is not yet compatible with the addons protocol used in stremio-web. That protocol is also not yet finalized. The only addon so far that works well with this client is [stremio-test-addon](https://github.com/Stremio/stremio-test-addon)

**Comment by madan81k** [comment]
ok. i was able to make it running, just for my learning purpose. just need to add another path with the tt name and it works.. but still there are problems around streaming server as it is hardcoded to localhost. so videos wont play :(

**Comment by nklhtv** [comment]
There is a pull request that i hope get merged soon #178
