### ISSUE TITLE
Web App

### ISSUE THREAD

**Issue by porfanid** [Stremio/stremio-web#190]
I am trying to run this as a web app on: [https://stremio-1.web.app/](https://stremio-1.web.app/) but there is something wrong with the plugins. What is going wrong? I cannot figure that out. 

The plugins can be installed but are not loaded

**Comment by nklhtv** [comment]
Cinemeta addon is not yet compatible with the addons protocol used in stremio-web. That protocol is also not yet finalized. The only addon so far that works well with this client is [stremio-test-addon](https://github.com/Stremio/stremio-test-addon)
