### ISSUE TITLE
[Feature] Filter by Year and Sort by Rating

### ISSUE THREAD

**Issue by thiagodp** [Stremio/stremio-web#192]
Filter By Year could show the best-rated movies and series at the top.

**Comment by danilomendonca** [comment]
+1

**Comment by nklhtv** [comment]
thats not a feature the could be implemented in the UI. It could be implemented by addons providing metadata

**Comment by danilomendonca** [comment]
Indeed: did it in 30 minutes, thanks to the neat platform architecture and rich examples.

https://github.com/danilomendonca/best-by-year
