### ISSUE TITLE
Question: Is the streaming server opensource

### ISSUE THREAD

**Issue by blackpr** [Stremio/stremio-web#193]
Hello, I'm not sure if this is right place for this question.
Feel free to close the issue

So I can see on settings that I can change the streaming server url.
The question is if I can find the steaming server code. Or the only option is to install stremio desktop.

Thanks

**Comment by Ivshti** [comment]
It's not open source yet - it's not published on a repo, but the JS is still available unminified here: https://dl.strem.io/four/master/server.js

you can download it and run it with nodejs (we recommend version 8 or 10) like this: `node server.js` - and this is enough to get it running on port 11470

**Comment by jaruba** [comment]
There is actually also a community built docker image for it: https://github.com/sleeyax/stremio-streaming-server
