### ISSUE TITLE
Error(Env) - Serialization error: data did not match any variant of untagged enum ResourceResponse

### ISSUE THREAD

**Issue by mozgbrasil** [Stremio/stremio-web#194]
Hello good afternoon all right ?

I performed the initialization of the environment

When accessing the project is displayed

    Error(Env) - Serialization error: data did not match any variant of untagged enum ResourceResponse

can you help me

![Captura de tela de 2020-09-28 17-10-13](https://user-images.githubusercontent.com/17202780/94481014-7e9b2980-01ad-11eb-876d-06e91d3cd677.png)

**Comment by nklhtv** [comment]
the issue was with the addons data not matching the new schema, should be fixed now

**Comment by pbaptista674** [comment]
dá este ero no TV quando faço a leitura do QR, Error(Env) - Serialization error: data did not match any variant of untagged enum ResourceResponse

**Comment by pbaptista674** [comment]
dá este erro quando pretendo entrar via pc: Error(Env) - Serialization error: data did not match any variant of untagged enum ResourceResponse

**Comment by TRtomasz** [comment]
@pbaptista674  please use english only when communicating on github

**Comment by Hny-B-King** [comment]
Happening to me, tried cleaning my trakt watchlist but didn’t help. Any solution to this, everything was working fine few days ago
