### ISSUE TITLE
Issues with air dates/released

### ISSUE THREAD

**Issue by TRtomasz** [Stremio/stremio-web#205]
**Description**
Where there are no dates for episodes we should display "TBA" or something like this at the moment we do not show anything, with this UI will be more consistent. Also i have no idea what does mean `10` or `50` after dates . Looks like this is release year i guess we should show full year
Tested with https://1fe84bc728af-test-mixed-released.baby-beamup.club/mixed/manifest.json
**Screenshots**
![image](https://user-images.githubusercontent.com/40594253/105491117-b9215880-5cad-11eb-9bd1-23316bd6adee.png)

**Comment by clarammdantas** [comment]
I would like to work on this issue. But I have a question.
Shouldn't TBA be used for episodes that didn't air yet? But in this case, it seems like we just don't have the release date information, although the episode did air, so TBA doesn't seem a good value to put in this field.

**Comment by nklhtv** [comment]
Done
