### ISSUE TITLE
Set focus on add addon text field

### ISSUE THREAD

**Issue by TRtomasz** [Stremio/stremio-web#207]
**Description**
When we click "add addon" button focus should be set to the text field, at the moment it is not 
**Screenshots**
![image](https://user-images.githubusercontent.com/40594253/105492509-f25ac800-5caf-11eb-983f-68c964bb86bb.png)

**Comment by nklhtv** [comment]
Still we have to implement it for all other modals with text input, like streaming server url modal

**Comment by vczb** [comment]
hi @nklhtv I just send a PR with this implementation
