### ISSUE TITLE
Invalid released date breaks details view

### ISSUE THREAD

**Issue by TRtomasz** [Stremio/stremio-web#208]
**Description**
Tested with
https://1fe84bc728af-test-mixed-released.baby-beamup.club/invalid/manifest.json
in the screenshot difference between stremio 5 and 4 
**Screenshots**
![image](https://user-images.githubusercontent.com/40594253/105492763-53829b80-5cb0-11eb-9ab0-d854ade735e1.png)
![image](https://user-images.githubusercontent.com/40594253/105492799-6006f400-5cb0-11eb-987e-65be366d4b77.png)

**Comment by nklhtv** [comment]
if deserializing one prop from an addon response fails we reject the entire response

**Comment by TRtomasz** [comment]
Not sure if this is desired behaviour, users might be confused and thinks that's a stremio issue.
@jaruba
