### ISSUE TITLE
Add a way to refresh thumbnails and posters

### ISSUE THREAD

**Issue by roydbt** [Stremio/stremio-web#210]
Using both the website version and the desktop client, the longer I use both versions the more I notice the desktop client has older and outdated posters compared to the website. I figured it was because the desktop client saves the poster instead of re-downloading them every time and the website does not. Why isn't there a button that makes the desktop client do exactly that?

**Comment by TRtomasz** [comment]
Hi @roydbt  first of all this repository is for stremio 5 version. For stremio features idea you should use stremio-features repository.
Anyway i will answer your question here. Posters and all other images are cached to reduce traffic presure on the servers. In many cases we use api that has some request limits so with feature like this we make whole system vunerable in many ways including things like getting blocked by api providers, gettin ddosed by users who would refresh images all the time.
