### ISSUE TITLE
Mobile version of Stremio Web 

### ISSUE THREAD

**Issue by amzero** [Stremio/stremio-web#219]
My smart TV LG Browser(Chrome Based) can't open the Web server running on my Laptop.
Many kinds of services the browser can't open. It normally opens newer codes. It doesn't open webpages with flash, for example.
I guess a Mobile version of the service could open on it.

I guess it's a enhancement.

*I'm noob in code and github. My first related issue.

**Comment by deniscerri** [comment]
Get a cheap chromecast so u wont worry about that anymore. Smart TV Browsers are pretty lackluster and eventually will become unusable after some time, even if developers try to fix the issue now. I have a lg tv too and got a chromecast

**Comment by nklhtv** [comment]
We target all major desktop browsers. TV devices are not in our target list, but we could add them soon.
You could try running [stremio 4](http://app.strem.io/shell-v4.4/#/) or use some of the casting methods available in the desktop app.
