### ISSUE TITLE
When playback fails, we should show a message with a button to download an M3U playlist with the stream URL

### ISSUE THREAD

**Issue by jaruba** [Stremio/stremio-web#227]
If playback fails in the web player (if the Stremio Server is not running in order to transcode the video) we should show a message that the video cannot be played in the web player and a button to "download playlist".

The download playlist button should generate an M3U playlist and force download, all local video players should already support M3U playlists, so just opening the downloaded file should start the stream with the local video player.

I prepared some example code that generates an M3U playlist with JS, includes the stream title and stream URL:
```
<a id="downloadlink" href="" download="playlist.m3u">m3u file</a>
<script>
	const streamUrl = 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/1080/Big_Buck_Bunny_1080_10s_1MB.mp4'
	const streamName = 'Big Buck Bunny'
	const playlist = '#EXTM3U\n\n#EXTINF:0,' + streamName + '\n' + streamUrl
	document.getElementById('downloadlink').href = 'data:application/octet-stream;charset=utf-8;base64,' + window.btoa(playlist)
</script>
```

We can also expand on this method by adding the subtitle URL too, but this is only supported by VLC (the other video players would ignore this feature). Here is an example of a M3U file that supports passing a subtitle too:
```
#EXTINF:-1,Abenobashi ED - Anata No Kokoro Ni (In Your Heart)
#EXTVLCOPT:sub-file=/p/Documents/mus/lyrics/Abenobashi ED - Anata No Kokoro Ni (In Your Heart).srt
#EXTVLCOPT:subsdec-encoding=UTF-8
Abenobashi ED - Anata No Kokoro Ni (In Your Heart).flv
```

**Comment by nklhtv** [comment]
done
