### ISSUE TITLE
Stream is not supported?

### ISSUE THREAD

**Issue by JoaoLeonello** [Stremio/stremio-web#238]
Keep getting this error on Debian Buster, found this webapp option because desktop version isn't working on debian 10 even when installed with flatpak (some issue with libmpv1 (>= 0.30.0) and buster's being lower than that). Think maybe it's the same issue?

![image](https://user-images.githubusercontent.com/55457001/126045284-2badace8-e112-4fcc-97a9-2dccc4bbe52d.png)

**Comment by dongphuchaitrieu** [comment]
I have same problem, anyone knows how to fix this?

**Comment by JoaoLeonello** [comment]
> I have same problem, anyone knows how to fix this?

definitaly an issue with some lib, upgraded to debian 11 and now it works
