### ISSUE TITLE
"Failed to fetch" to all torrents.

### ISSUE THREAD

**Issue by amzero** [Stremio/stremio-web#241]
Every time i try to play a torrent in browser in the same host that the desktop version is running, i get "Failed to fetch". I can't run any torrent. I only tried with torrents.

**Comment by Cemvegas** [comment]
Hi Angela,

Make sure the link you use in your browser is the same as the "Streaming 
Https endpoint" link in your Stremio settings

21.08.2021 18:48 tarihinde Angelo Morgan yazdı:

**Comment by amzero** [comment]
Oh, right. It worked! 
Let me explain better:

Same machine, running .exe and web version.

- When i use localhost:11470, the torrents loads.
- When i use my local IP 192.168.1.5:11470, "Failed to fetch".
- But the option "Enable remote https connections" automatically gets my ip and create the correct link. that works.
- I don't understand english so much, but, this "Enable remote https connections" option, i guess it is not made very well. 
-The option "Streaming server URL" already means that you can use the web version, but with no httpS, only http.
- The "Enable remote https connections" that i understood, means that is to only enable httpS connections.
- And the "Streaming server is available" means to me that the web version is running perfectly.

I think someting is confusing, or my english is weak.
Thanks for help.

**Comment by amzero** [comment]
And the link that "Streaming HTTPS endpoint" gerates, is too complex to remember and use in another browser in another computer. The 192.168.1.5:11470, i think it's perfect to run in other machine, using a different machine as a server.

**Comment by TRtomasz** [comment]
Hello, i dont think this feature is supported now in stremio-web version. @nklhrstv  could you confirm?

**Comment by Cemvegas** [comment]
hello angela, i suffered the same problem as you for a long time. 
However, this is the only solution I could find. And now you can stream 
torrents with this method even another computer or tv if they are in 
same LAN with subtitles. I hope it helped.

23.08.2021 22:24 tarihinde Angelo Morgan yazdı:
>
> Oh, right. It worked!
> Let me explain better:
>
> Same machine, running .exe and web version.
>
>   * When i use localhost:11470, the torrents loads.
>   * When i use my local IP 192.168.1.5:11470, "Failed to fetch".
>   * But the option "Enable remote https connections" automatically
>     gets my ip and create the correct link. that works.
>   * I don't understand english so much, but, this "Enable remote https
>     connections" option, i guess it is not made very well.
>     -The option "Streaming server URL" already means that you can use
>     the web version, but with no httpS, only http.
>   * The "Enable remote https connections" that i understood, means
>     that is to only enable httpS connections.
>   * And the "Streaming server is available" means to me that the web
>     version is running perfectly.
>
> I think someting is confusing, or my english is weak.
> Thanks for help
>

**Comment by TRtomasz** [comment]
Hello,
this repository is for stremio-web has not been released yet. If you have any problems with stremio 4 application please use stremio-features or stremio-bugs repositories.
