### ISSUE TITLE
Change audio track

### ISSUE THREAD

**Issue by coolwormgit** [Stremio/stremio-web#242]
Is there any way to change audio language on stream? for example Stremio shows 2 Tracks but only the first working!

Thank you

**Comment by TRtomasz** [comment]
Not sure if this questions is for stremio-web or Stremio 4 application. 
If this is for stremio 4 then, yes it is possible. When there are more audio tracks available then DUB icon should be visible. 
If one audio track is not working then perhaps it is something wrong with the file.

**Comment by coolwormgit** [comment]
Is for stremio Web, i can see the DUB tracks but i cant change...
thanks
