### ISSUE TITLE
MPV?

### ISSUE THREAD

**Issue by varlesh** [Stremio/stremio-web#243]
Stremio desktop app use MPV as default.
Stremio web requires running Stremio Desktop, BUT NOT USE MPV PLAYER?
What is this?
Why Stremio-web needed stremio-desktop server, but not mpv?
Built-in player no support popular codecs and i'm have error with transcode.
What you doing devs?!

**Comment by varlesh** [comment]
app.strem.io:
![Screenshot_20210831_184354](https://user-images.githubusercontent.com/8083855/131523988-db67081b-4e8c-4e2a-8684-fa268596f9c8.png)
stremio-web:
![Screenshot_20210831_184432](https://user-images.githubusercontent.com/8083855/131524046-22e67d47-4699-4da0-abde-e540cc6221bf.png)

**Comment by varlesh** [comment]
Why this worked on app.strem.io, but NOT on stremio-web?

**Comment by TRtomasz** [comment]
Stremio web has not been released yet it is work in progress.

**Comment by varlesh** [comment]
app.strem.io it's not web-version?

**Comment by varlesh** [comment]
I can open issue about "Failed to create transcoder". It's needed?

**Comment by varlesh** [comment]
You are opensource? Seriosly?

**Comment by TRtomasz** [comment]
app available here http://app.strem.io/shell-v4.4/#/
and app that is available in this repository are two separate aplications

**Comment by varlesh** [comment]
OK, where source code this page? http://app.strem.io/shell-v4.4/#/

**Comment by TRtomasz** [comment]
This app is not open-source.

**Comment by varlesh** [comment]
It's fine!

**Comment by varlesh** [comment]
https://www.stremio.com/
![Screenshot_20210831_192925](https://user-images.githubusercontent.com/8083855/131531609-14fe5faf-aede-4d7b-bfc1-d4a836fa754d.png)

**Comment by sleeyax** [comment]
http://app.strem.io/shell-v4.4/#/ is a part of Stremio **version 4**, which is not fully open source.

This repository, `stremio-web`, contains source code for Stremio **version 5** which is fully open source. Stremio 5 is still a WIP, so things might not work as expected.

**Comment by varlesh** [comment]
I'm understand that commercial  move and monetize this project  - it's necessary.
I'm really not understand...  Why you don't want make Tizen, WebOS versions - it's thousands potential users.
I can't use it, because you are write tabindex limit. And you are don't want port blob's to opensource

Donate it's not your way?
