### ISSUE TITLE
Support for Android TV

### ISSUE THREAD

**Issue by emlautarom1** [Stremio/stremio-web#244]
AFAIK, the current UI for Android is based on v4.4 - same as desktop. This brings a couple of usability issues related to navigation with a remote instead of touch controls/mouse & keyboard when using Stremio from Android TV. When I started to look for the code of the current Android version I found that it's closed source, and that regarding UI the next version (v5) would be open source (this repo).

I was wondering if this UI will be eventually the one shipped for Android, and if so, how is remote navigation handled? I read on https://github.com/Stremio/stremio-web/issues/219 that TV's are not your focus, but since it's my main driver for Stremio I think I could help with that. Also, would it be possible to run the new UI from an Android device (mainly for testing)?

**Comment by nklhtv** [comment]
we dont have plans to add support for Android TV to this project
