### ISSUE TITLE
How to build this

### ISSUE THREAD

**Issue by NoChizPlz** [Stremio/stremio-web#247]
Hello im trying to run this but im getting this error

fatal: not a git repository (or any of the parent directories): .git
[webpack-cli] Failed to load '/Users/joshualictan/Downloads/stremio-web-5.0.0-alpha7/webpack.config.js' config
[webpack-cli] Error: Command failed: git rev-parse HEAD

and i followed the README.md it doesnt work

**Comment by jota3c** [comment]
_fatal: not a git repository (or any of the parent directories): .git_
Run first : git init

**Comment by NoChizPlz** [comment]
> _fatal: not a git repository (or any of the parent directories): .git_ Run first : git init

after building how to start it?

**Comment by sleeyax** [comment]
`npm start`

**Comment by g3r451m** [comment]
it says webpack not found

**Comment by nklhtv** [comment]
First you need to clone the repository properly, using git, not by downloading a tar ball.
Then you can follow the instructions in the [README](https://github.com/Stremio/stremio-web#build)
