### ISSUE TITLE
Something went wrong cat image

### ISSUE THREAD

**Issue by Ghudza** [Stremio/stremio-web#264]
I have build it already but now its showing this whenever u put the Index.html in my browser (i have tried 3 separate browsers to no effect)
can anyone help me on this ?
![image](https://user-images.githubusercontent.com/69442934/152906802-8fb8612a-184f-4b1d-9306-f4bcae29f15c.png)

**Comment by nklhtv** [comment]
could you tell me whats the value of window.services.core.error

**Comment by nklhtv** [comment]
for some reason stremio-core failed to initialize successfully, the reason can be seen in the logs.
reopen this issue when you have more details
