### ISSUE TITLE
Open Subtitles - "Cannot Find Addon/Collection from this URL"

### ISSUE THREAD

**Issue by ghost** [Stremio/stremio-web#266]
Hi, I'm trying to configure _OpenSubtitles_, but I keep getting the error messages: 

"Cannot Find Addon/Collection from this URL"

"ERR_OPENING_MEDIA"

Any Ideas?

**Comment by TRtomasz** [comment]
Sorry, there is nothing we can do to fix community addons, and we do not have any contact to this addon creator to notify him
