### ISSUE TITLE
Please don't use version ranges in transitive dependencies

### ISSUE THREAD

**Issue by Arcitec** [Stremio/stremio-web#286]
Hi! The `package.json` file has a bad dependency specification:

```
"webpack-cli": "4.9.1",
```

It specifically points at a broken version of webpack-cli. The title of this post is a quote from the webpack-cli developers, saying that you should never specify an exact version of webpack-cli. Always specify a "compatible with" semver specifier instead, so that bugfixes can install themselves.

https://github.com/webpack/webpack-cli/issues/3294

**Comment by Arcitec** [comment]
The correct way to specify the version:

```
"webpack-cli": "^4.9.1",
```

This of course goes for other packages that obey semantic versioning too. This one just happened to be the one that broke. :)

**Comment by nklhtv** [comment]
with or without `^` updates wont install themselves unless someone run `npm update` for that package, which is almost the same work as modify the version in package.json.
i can see that using `^` in package.json can be very beneficial for libraries and will consider apply those changes in stremio-core-web, stremio-video etc, but not here.
in the past weve got many issues with js packages that dont follow the semver spec and introduce api changes in patch updates so i prefer to update everything manually.
