### ISSUE TITLE
Streaming server query parameter not working

### ISSUE THREAD

**Issue by Conventional-programmer** [Stremio/stremio-web#295]
When hosting my own stremio web server the streaming server query parameter doesn't seem to be working on my local install of stremio-web. My local install is a build of the latest version from git running on http-server.
![Schermopname (379)](https://user-images.githubusercontent.com/55490231/163217783-0dcba47f-65d3-4d2d-bd7a-a79975b31980.png)
![Schermopname (377)](https://user-images.githubusercontent.com/55490231/163217784-4b5e3c1c-c59f-4b23-83a3-f6e4f612917c.png)

**Comment by josephcomisi** [comment]
Hi, same issue here. Server version 4.18.0. Works fine with UI v4.4.151

**Comment by nklhtv** [comment]
Hi @Conventional-programmer We dont have this feature in stremio-web, but you can override the streaming server url in the settings page, by clicking on the gear icon.

**Comment by nklhtv** [comment]
We will consider bringing this feature to stremio-web too if its needed.

**Comment by josephcomisi** [comment]
Hi @nklhtv , the problem is mainly on stremio-web.
I use the Mac OS app, version 4.18.0, for the server part.
I can connect to the server by using the UI v4.4.151 http://app.strem.io/shell-v4.4/#/
But if I build the stremio-web, and change its settings (the same way as I do with the shell 4.4), then it does not work.

**Comment by Goldenfreddy0703** [comment]
Hey @nklhtv , sorry to bother you but is there anyway we could bring this feature, Reason why i think it could be needed is so i can use the playback. Sometimes on the old stremio web, it gives me playback errors and i understand when it comes to torrents and services but on the Stremio 5.0.0, its been working flawlessly, the only downsides im having is the Trakt Scrobbling and the streaming server for other devices. I really love this new modern version of Stremio and its amazing.

**Comment by nklhtv** [comment]
Could you give me more details about how exactly it fails.
What url you use to access stremio-web?
What url you use for the stremio-server?
What errors you have in the console/network tab?

**Comment by Goldenfreddy0703** [comment]
Hey there, it's been a month sense I tried Stremio but if I remember, Torrentio was the addon that gives me playback errors on the old stremio but works flawlessly on the new stremio.

The url was probably my local ip address to access stremio web in the past.

For the stremio server it self, it was basically running on my Linux server which I can access using my ip to that device. 

Console errors, I don't recall except that the streaming server status was giving an err on this new version Stremio

**Comment by nklhtv** [comment]
Then I suspect that was some CORS issue. Did you use `localhost` or the ip address for configuring the streaming server?

**Comment by Goldenfreddy0703** [comment]
I believe I used localhost

**Comment by afonsofrancof** [comment]
> We will consider bringing this feature to stremio-web too if its needed.

This would be nice since the web page provided by the new docker image is the old web ui.
I believe this is because we can use query parameters on the old web ui and auto apply the correct streaming server.
It would be nice if it could redirect to the new Web UI but for that query parameters would need to be implemented.

**Comment by TRtomasz** [comment]
this is implemented now
