### ISSUE TITLE
Error Message: Stream is not supported

### ISSUE THREAD

**Issue by itaibaruch** [Stremio/stremio-web#301]
Hi,

I follow the readme file, and run the following commands (Macos 12.6 M1):
``` npm install ```
``` npm start ```
everything seems to work fine, I can login, and view youtube videos.
when I try one of the streamed videos, I get the error message "Stream is not supported" with an options to "open in external player".
how can I make the app "natively" play the stream? do I have to install something in advanced?

I try to make an app for LG tv WebOs :)

![Screen Shot 2022-09-20 at 18 06 18](https://user-images.githubusercontent.com/6505953/191242288-91e38266-1e23-4105-8a9e-fb9a82354f25.png)

**Comment by memerememe** [comment]
yoo, my thanks to you on attempting to make stremio for webos, have you made progress from this or are u still on this issue? would also love if you uploaded the webos ipk to a public repo as you progress on porting the app :-)

**Comment by itaibaruch** [comment]
Hi,

The short answer, No, I couldn't make the streaming work. It will be great if you can point me to some instruction of how to install and getting the player to work. reading [stremio-shell](https://github.com/Stremio/stremio-shell) didn't get me there.
and I will share the IPK, that's the whole purpose :)

**Comment by jharrvis** [comment]
> Hi,
> 
> I follow the readme file, and run the following commands (Macos 12.6 M1): `npm install` `npm start` everything seems to work fine, I can login, and view youtube videos. when I try one of the streamed videos, I get the error message "Stream is not supported" with an options to "open in external player". how can I make the app "natively" play the stream? do I have to install something in advanced?
> 
> I try to make an app for LG tv WebOs :)
> 
> ![Screen Shot 2022-09-20 at 18 06 18](https://user-images.githubusercontent.com/6505953/191242288-91e38266-1e23-4105-8a9e-fb9a82354f25.png)

Have you found the answer to this issue?
I'm experiencing the same issue, how to resolve the "Stream is not supported" error?

**Comment by itaibaruch** [comment]
I haven't found a solution for this :(

**Comment by memerememe** [comment]
noo, thats sad, 
Can you perhaps create a private repo which includes all the files and their changes and add me as a contributor(or public if you're comfortable with it, in which case i don't need contributor access since i can just see the files) so that i can see if i can find the issue?

**Comment by memerememe** [comment]
@itaibaruch @jharrvis ?

**Comment by jharrvis** [comment]
> noo, thats sad, Can you perhaps create a private repo which includes all the files and their changes and add me as a contributor(or public if you're comfortable with it, in which case i don't need contributor access since i can just see the files) so that i can see if i can find the issue?

in my case i didn't change anything, just cloned it and ran npm install, and npm start

![Cuplikan layar 2023-04-11 122641](https://user-images.githubusercontent.com/10702374/231064412-fc8f6de3-03fa-4b4f-960c-9d5ef86b7eb3.jpg)

**Comment by elpiel** [comment]
Hello everyone,
Thank you for the interest in the `stremio-web` application.
Sadly to fix this issue we still need to work on the server to allow media formats supported by the browsers.

This is the main issue you're facing with playing streams atm

**Comment by t3dkich** [comment]
Hey, I'm just facing same error. Are there any improvements on this? thanks

**Comment by elpiel** [comment]
There's a new release of the server.
Please let us know if the issue still consist with Stremio server >= 4.20.1

**Comment by itaibaruch** [comment]
so you right,
downloading the repo https://github.com/Stremio/server-docker
build: 
```docker build --build-arg VERSION=v4.20.1 -t stremio/server:latest .```
run:
``` docker run --rm -d -p 11470:11470 stremio/server:latest ```
opening browser on http://localhost:11470/ , and streaming is working.

keeping the docker image running, I try to run 
```npm start```
on this repo, but the stream still fail....

**Comment by elpiel** [comment]
You can also try passing `NO_CORS=1` to the docker container as env. variable.  `docker run -e NO_CORS=1 --rm -d -p 11470:11470 stremio/server:latest`

What I have to note as well is that there might still be streams that are unsupported on Web. Try a few other streams to double check if this is the case.
I did try with and without `NO_CORS=1` and I still got a few streams to load and play. Both in web and on the shell - https://app.strem.io/shell-v4.4/?streamingServer=http://localhost:11470#/settings

**Comment by itaibaruch** [comment]
```NO_CORS=1 ```
did the trick!

now I need to figure out how to bundle it and run it on LG WebOs IPK...

**Comment by elpiel** [comment]
> `NO_CORS=1 ` did the trick!
> 
> now I need to figure out how to bundle it and run it on LG WebOs IPK...

Awesome!
Please re-open the issue if you are experiencing any other issues related to supported stream.

**Comment by memerememe** [comment]
> `NO_CORS=1 ` did the trick!
> 
> now I need to figure out how to bundle it and run it on LG WebOs IPK...

this is amazing!now, i hope it will,  only be a matter of time if you or someone successfully compiles a IPK for webos!
