### ISSUE TITLE
500MB caching option?

### ISSUE THREAD

**Issue by K0-RR** [Stremio/stremio-web#333]
My Android TV only has 1,78 GB of free space available. When I'm using the smallest cache option available, my device is becoming less responsive and every minute I get a pop-up saying no more space available.
Please add the option to set cache to a few other values lower than 2 GB.
![image](https://user-images.githubusercontent.com/43277609/209478387-ab14530e-ff89-4eb4-9606-61b839fa877d.png)

**Comment by K0-RR** [comment]
Additionally, Stremio should have a check for a free storage and do not write to the disk if available is less than 100 MB.

**Comment by eon-pixel** [comment]
I'm guessing this is because some media files are often quite large (1GB+) and need a buffer of 2GB minimum? 

However, adding onto this, perhaps an option to choose the path where Stremio stores the cached data might be a good option? In situations like this, it might be beneficial to offload that cache to external storage rather than write it to the already small storage of the Android TV device.

> My Android TV only has 1,78 GB of free space available. When I'm using the smallest cache option available, my device is becoming less responsive and every minute I get a pop-up saying no more space available. Please add the option to set cache to a few other values lower than 2 GB. ![image](https://user-images.githubusercontent.com/43277609/209478387-ab14530e-ff89-4eb4-9606-61b839fa877d.png)

**Comment by TRtomasz** [comment]
Cache works in way that it will require as much space as big is file you are trying to play. If you try to play 20GB video and set cache size to 2gb it still will need 20GB and app will crash, thats why we remove cache size setting from android tv app.

**Comment by Kabouik** [comment]
An option to change cache location would still be useful. I use the `stremio-web` Docker image on a phone whose internal storage is limited, and would happily move the cache to its SD card.

I could do that with a symbolic link too, but this is more hacky and it's not clear to me where is the cache at the moment.
