### ISSUE TITLE
Show episode list when opening an episode from "Continue watching"

### ISSUE THREAD

**Issue by ghost** [Stremio/stremio-web#337]
The new behavior to open an episode from "Continue watching" is confusing without episide list, I can barely see what episode i'm on

![image](https://user-images.githubusercontent.com/70694330/210539426-3ee15aac-7e4a-4f8e-9148-bcb6e9a1d0fa.png)

The old one highlights the episide and keeps the list shown when opening. This is so much better

![image](https://user-images.githubusercontent.com/70694330/210539461-bbfa7167-8e7d-4a75-9ca3-6fce87163a16.png)

![image](https://user-images.githubusercontent.com/70694330/210539724-7a4524b5-9b04-4b1c-bdb7-e67bd4471245.png)

Can you bring the old behavior back or at least add an option to change it?

**Comment by elpiel** [comment]
One addition: This issue is present even if you open the given movie series from the Library.

We're working on the new design that will include the Episode & Season numbers along side a back-button to go to the list of Episodes & seasons with thumbnails.

**Comment by kKaskak** [comment]
This was implemented with 2 different way of clicking the item 
1. By Clicking the play button, you go to the episode / stream itself
2. By clicking the poster, you go to the episodes list
