### ISSUE TITLE
Support for XDG Base Directory specification 

### ISSUE THREAD

**Issue by Peltoche** [Stremio/stremio-web#351]
Hello,

First of all thanks for you work, this is a great project!

On linux I currently have the folder `.stremio-server/stremio-cache` living inside my `$HOME` folder. As I have setup the env variable `$XDG_CACHE_HOME` I would expect to see this folder inside `$XDG_CACHE_HOME/stremio-cache` in order to respect the XDG Base Directory specification and avoid to clutter the `$HOME` path.

Would it be possible to check if the env `$XDG_CACHE_HOME` is present and if it is use it instead of `$HOME/.stremio`?

**Comment by TRtomasz** [comment]
https://github.com/Stremio/stremio-bugs/issues/448
