### ISSUE TITLE
Avatar image has `background-image: url("null")`

### ISSUE THREAD

**Issue by elpiel** [Stremio/stremio-web#356]
```
style='background-image: url("null"), url("https://localhost:8080/dddc390952a46a9303da0bb88789bbe7c22ddc95/scripts/../../dddc390952a46a9303da0bb88789bbe7c22ddc95/images/default_avatar.png");'
```

**Comment by pravinargade18** [comment]
Sir, could you please explain this issue to me in more detail?

**Comment by elpiel** [comment]
@pravinargade18 when a logged-in user doesn't have an avatar it shows 2 different `backgroun-image` `url`s in the source code, even though the browser fails back to the second URL, it still shows an error in the console when trying to load `url(null)`:

The lines affected are here:
https://github.com/Stremio/stremio-web/blob/5705233705ec5d5bd360ca855ed187cc855ea5a7/src/routes/Settings/Settings.js#L212

It doesn't affect the application but it would be nice to remove this error when there's no set avatar for the user.

Would you like to open a PR to fix this?

**Comment by Iheuzio** [comment]
I fixed the two locations for the profile images. #361
