### ISSUE TITLE
[Feature] Splash screen with loading indicator

### ISSUE THREAD

**Issue by elpiel** [Stremio/stremio-web#358]
Right now on Desktop when you start a given stream it shows:
- a background image - poster of the movie/series
- Loading indicator - the title of the movie/series as a loaded indicator before it can start playing the stream

Currently the splash screen used in Web is the Stremio logo with no loading indicator:

![image](https://user-images.githubusercontent.com/8925621/233292540-ded5e20b-4128-49d4-96dd-f01fdce768c1.png)

**Comment by Iheuzio** [comment]
You want it with the background images here?
![image](https://github.com/Stremio/stremio-web/assets/97270760/4ce5334f-6d90-49d2-96c4-a42b4ac7637e)

Also for loading a buffer, that could be done with the flashing logo atop the background image provided above with the bitrate displayed. I can work on those later if that sounds good.

**Comment by elpiel** [comment]
@Iheuzio thank you for your interest. Actually this was already implemented in `stremio-web`.
There is currently a bug where it can take a long time to show the splash screen if the stream hasn't started loading yet.

![image](https://github.com/Stremio/stremio-web/assets/8925621/119fae73-eae0-488e-a889-6de1430697b0)

but once the stream starts loading you can see the splash screen

![Screenshot from 2024-03-01 17-07-34](https://github.com/Stremio/stremio-web/assets/8925621/e3564395-dfaf-4bb9-8a39-ae47c53403e8)

cc @tymmesyde
