### ISSUE TITLE
[Feature] Save progress on movies/series

### ISSUE THREAD

**Issue by secrecyflag** [Stremio/stremio-web#367]
This already exist in the mobile app, it would be really helpful if it would also in web.
Save the current timestamp on an episode/movie, so we could resume after an exit or other.

**Comment by kKaskak** [comment]
This is already implemented tho closing this issue -->

<img width="184" alt="Screenshot 2024-03-28 at 20 47 50" src="https://github.com/Stremio/stremio-web/assets/117831817/cc7dce86-3277-4eb2-8e1e-3e975bb67055">
