### ISSUE TITLE
No Player setting for external Player to enable.

### ISSUE THREAD

**Issue by jfmusic** [Stremio/stremio-web#391]
Please explain how to get around this.

thanks

**Comment by jfmusic** [comment]
Must get to site via link or it doesn’t work.

**Comment by TRtomasz** [comment]
Please update your ticket to provide minimal reproducible exmaple of the issue.(steps to reproduce) from your message it is not possible to understand what is wrong.

**Comment by jfmusic** [comment]
Without locating the website from your link, and then trying to use the app on the phone there was no Display Chenge setting button. I fixed after going back to your write and the specific link. Works now thanks
