### ISSUE TITLE
Unable to build Dockerfile

### ISSUE THREAD

**Issue by J-Stuff** [Stremio/stremio-web#393]
It is not possible to build the Dockerfile because `stremio/node-base:fermium` is not public

**Comment by elpiel** [comment]
Yes, we are looking into using the official node version.
If you want to give it a try, we'll be glad to review your PR.

**Comment by sleeyax** [comment]
But why isn't `stremio/node-base:fermium` public? Is there something special about that Docker image that should be taken into account?

**Comment by elpiel** [comment]
@sleeyax this particular image is based on node but has some ssh keys added for accessing private repos.
As far as I was told, they are only needed for `stremio` and not `stremio-web` so we can just try to replace it with the official one.

**Comment by antidoid** [comment]
Hey, is it still up for grabs, assign me to it, I would love to work on it

**Comment by kerashanog** [comment]
Hi @elpiel,

Could you take a look at my PR? This will replace your private image with Official Node image.
Also, I made multi stage build to to reduce the size of the final image.

**Comment by elpiel** [comment]
Closing this issue.
We've merged the change to an official docket image.
