### ISSUE TITLE
Can't change audio tracks

### ISSUE THREAD

**Issue by SupraKarma** [Stremio/stremio-web#395]
You can change audio tracks in version 4 of stremio web - https://i.ibb.co/LNw5c29/version-4.png, whereas version 5 doesn't even have that option - https://i.ibb.co/WB4YdyY/version-5.png. This is essential if you're playing torrents with multiple audio tracks, foreign audio or audio commentary.

**Comment by PaprikaBoyTheOneAndOnly** [comment]
Issue still exists. If I download the mkv file directly from my debrid I can see that the file has multiple audio streams. Also, the `/hlsv2/probe` request returns two audio tracks (see attachment) although I am not entirely sure if this is the right lead.
![image](https://github.com/user-attachments/assets/dabe5c5d-bf32-46b9-89e8-488b98e6de5b)

**Comment by tymmesyde** [comment]
Hi, you can already change the audio track if you have the server available, but it's not very intuitive, on the subtitles menu on the left

**Comment by PaprikaBoyTheOneAndOnly** [comment]
Hi @tymmesyde, thanks for you fast reply. I do know the audio change feature and for some of the streams the change does work. But there are some instances where the button is disabled even though multiple audio streams are available. I also tried to enable the button by editing the css but then no no audio stream is displayed.
