### ISSUE TITLE
No videos found for this meta

### ISSUE THREAD

**Issue by GunGunGun** [Stremio/stremio-web#399]
URL: [/#/detail/movie/tt15830702](https://web.strem.io/#/detail/movie/tt15830702)

Is this expected or it'll be added in the near future ? It works fine in Stremio Desktop or `http://127.0.0.1:11470/`, but not `https://web.strem.io`

![image](https://github.com/Stremio/stremio-web/assets/6913739/3eb86a72-ca5b-49dd-83bd-0f655ae4cc2c)

**Comment by TRtomasz** [comment]
First of all Stremio does not controll any available content it is provided by addon so no we can't add anything
Second of all you have wrong link https://web.stremio.com/#/detail/movie/tt15830702/tt15830702
