### ISSUE TITLE
[Epic] Player: unified, formalized interface

### ISSUE THREAD

**Issue by Ivshti** [Stremio/stremio-web#4]
Can we unify the interface to a player as a read/write stream of events? This would replace/simplify stremio-cast (also see this: https://github.com/Stremio/labs/issues/3), replace `models/player.js` and potentially bring a unified way to build in `stremio-web` and `stremio-rn`

Also, this might make things like `telepathy` easier to implement. Also the state of the player UI can be just the stream of events ran through a reducer. This is kinda similar to the concept of react state containers

**Comment by nklhtv** [comment]
no longer relevant, replaced by the player specs
