### ISSUE TITLE
Cannot change subtitle color in LGTV WebOS browser

### ISSUE THREAD

**Issue by GoToNap** [Stremio/stremio-web#401]
Unfortunately as we all know, there's no WebOS Stremio app at the moment, however, using the Stremio Web version in the WebOS browser is pretty ok.

There's one glaring issue though. Unfortunately changing the subtitle color is not possible due to the fact that when you click on that option nothing happens, as a color box should pop up which apparently is not supported on LG's browser.

For people like me with problematic vision this is a deal breaker when it comes to HDR / Dolby Vision content as we're stuck with a pure white version which makes us go blind after a couple of minutes.

It would be awesome if a drop-down menu would be introduced with some preset options to circumvent the browser's limitation (please include both gray and dark gray options if this is done)

Thanks!

**Comment by SupraKarma** [comment]
I have the same issue, but only on v4 of Stremio Web (where DV/HDR has better compatibility), on v5 I can change the color of subtitles. Actually it's the only thing I like about v5 in comparison to v4.

**Comment by GoToNap** [comment]
> I have the same issue, but only on v4 of Stremio Web (where DV/HDR has better compatibility), on v5 I can change the color of subtitles. Actually it's the only thing I like about v5 in comparison to v4.

How do I get the v5 web version?

**Comment by GoToNap** [comment]
So I have no idea what happened, but I just tried it again in the WebOS browser and the color picker pop up showed up!

Subtitle color can finally be changed!
