### ISSUE TITLE
help me please guys 😭

### ISSUE THREAD

**Issue by Moribax** [Stremio/stremio-web#415]
Hey guys,  why choice ( open stremio ? ) not showing ......help me please guys 😭👍🏿
![image](https://github.com/Stremio/stremio-web/assets/110537768/59a8e3f1-bd5a-4cc7-b72d-4661812b54ef)

**Comment by bartche** [comment]
This repo is for the Stremio Web version, not the Stremio Windows one. To install add-ons you must copy the manifest link and paste in the "Add Addons" button in the "Addons" tab.
Alternatively, you can install the Windows version than it should apper the "Open Stremio" you want.

**Comment by elpiel** [comment]
@bartche is correct.
If you have either Stremio desktop or stremio service you will be able to see Stremio as an option when you're opening `stremio://` urls.
Also see the browser settings because the have associated programs to given url schemes as well

**Comment by Moribax** [comment]
> This repo is for the Stremio Web version, not the Stremio Windows one. To install add-ons you must copy the manifest link and paste in the "Add Addons" button in the "Addons" tab. Alternatively, you can install the Windows version than it should apper the "Open Stremio" you want.

thank you so much brother its fixed 💗

**Comment by Moribax** [comment]
> 

thank you ....,

**Comment by elpiel** [comment]
You're welcome.
if you encounter any additional issues don't hesitate to open a new issue.
