### ISSUE TITLE
Stremio web player video is blank

### ISSUE THREAD

**Issue by HeartwinJ** [Stremio/stremio-web#423]
I have the Stremio Desktop client running, and it does say it is connected on the web version. I am able to access my library, and stream content. But when it is playing, I can only hear the audio, and see the subtitles. The video seems to be just blank.

![image](https://github.com/Stremio/stremio-web/assets/23290346/f9e50f61-42d7-47fa-bd42-738489a8fd40)

Here is a screenshot of what I'm seeing.

**Comment by TRtomasz** [comment]
Please try enabling hardware accelerated decoding in the settings and then check again.
Also what browser is this? If this is happening in firefox pleaase try using chrome.

**Comment by jaruba** [comment]
@HeartwinJ
what browser is that? is it firefox? if so, then firefox does not support all video decoders, chrome has better video support
if video / audio decoders don't work (even if the browser does not support it), it also means that you did not connect the server (check the web app settings and see if it says that the server is online, i presume it is not)

**Comment by HeartwinJ** [comment]
@TRtomasz Hardware accelerated decoding is already enabled, and I can't seem to even change it.

@jaruba I am on Edge

**Comment by jaruba** [comment]
@HeartwinJ did you look in the stremio web settings? does it say that the server is online? have you installed Stremio Service and is it running on ur system?

**Comment by HeartwinJ** [comment]
@jaruba It does say it is online. I have the Stremio Desktop client running.

![image](https://github.com/Stremio/stremio-web/assets/23290346/4d27c013-bafa-4263-8e38-c2b46a551ce1)

I can also confirm, that using Chrome does not resolve this issue. It is the exact same behavior there.

**Comment by jaruba** [comment]
what does it show if you go to http://127.0.0.1:11470/hwaccel-profiler

**Comment by HeartwinJ** [comment]
@jaruba

`["nvenc-win"]`

**Comment by jaruba** [comment]
maybe the chosen hardware acceleration profile is causing an issue on ur device

are you using Stremio Service or Stremio Desktop v4.4 as the server for the web app?

both the apps have a `server-settings.json` file, you should edit this file and set `"transcodeProfile": false` (most probably it is `"transcodeProfile": "nvenc-win"` now)

for the desktop app, i think the location of this file is `%appdata%\stremio`

**Comment by HeartwinJ** [comment]
@jaruba I am using Stremio Desktop as the server.

I changed `transcodeProfile` to 'false`, but that didn't change anything.

Something I have also noticed is that if I restart Stremio Desktop, the setting is reverted back to `nvenc-win`

**Comment by jaruba** [comment]
try setting both `"transcodeHardwareAccel": false` and `"transcodeProfile": false`

**Comment by HeartwinJ** [comment]
Now, the change persists, but it doesn' t solve the issue. The stream istill blank.

Here is the entire settings, in case it helps you:

```json
{
    "serverVersion": "4.20.0",
    "appPath": "C:\\Users\\heart\\AppData\\Roaming\\stremio\\stremio-server",
    "cacheRoot": "C:\\Users\\heart\\AppData\\Roaming\\stremio\\stremio-server",
    "cacheSize": 2147483648,
    "btMaxConnections": 55,
    "btHandshakeTimeout": 20000,
    "btRequestTimeout": 4000,
    "btDownloadSpeedSoftLimit": 2621440,
    "btDownloadSpeedHardLimit": 3670016,
    "btMinPeersForStable": 5,
    "remoteHttps": "",
    "localAddonEnabled": false,
    "transcodeHorsepower": 0.75,
    "transcodeMaxBitRate": 0,
    "transcodeConcurrency": 1,
    "transcodeTrackConcurrency": 1,
    "transcodeHardwareAccel": false,
    "transcodeProfile": false,
    "transcodeMaxWidth": 1920
}
```

**Comment by TRtomasz** [comment]
@HeartwinJ  can you please tell us which stream you are trying to play?

**Comment by HeartwinJ** [comment]
@TRtomasz I am using Torrentio to get the streams.

**Comment by jaruba** [comment]
Are you trying to watch 4K content? Does 1080p content work? Does your display support 4K resolution?

**Comment by HeartwinJ** [comment]
@jaruba I am on a 4k screen, but I am trying to stream1080p

**Comment by realsontaran** [comment]
I have the same issue. Using Firefox, but it gave same result with chromium as well on arch linux.

**Comment by TRtomasz** [comment]
@HeartwinJ  so i assume you are on windows, could you please which stream exactly you have tried to play? just select it on a screenshot.
Also, are you using stremio-service or maybe regular stremio desktop app as your streaming server?
