### ISSUE TITLE
How TO RUN?

### ISSUE THREAD

**Issue by kata62** [Stremio/stremio-web#430]
after complete
Build
Prerequisites
Node.js 12 or higher
npm 6 or higher
Install dependencies
npm install
Start development server
npm start
Production build
npm run build

How TO RUN?

**Comment by elpiel** [comment]
Hello, thanks for reaching out.
You can run stremio-web by:

> Start development server
> npm start

It will then show you that you can reach out the server at specific url:

```
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:8080/
<i> [webpack-dev-server] On Your Network (IPv4): http://192.168.0.215:8080/
```

go to localhost:8080 and should see `stremio-web`.

Please, don't hesitate to re-open the issue if this is not the answer you were looking for.
