### ISSUE TITLE
Streaming URL hostname is wrong

### ISSUE THREAD

**Issue by r0hin** [Stremio/stremio-web#431]
Copying the streaming URL yields something like:

```http://10.0.0.140:11470/...``` ... which does not work, rather than using the hostname provided in streaming URL in settings (which does work)

When opening the stream in external player, it also does not work.

**Comment by edde746** [comment]
This is an issue in `stremio-core` by the looks of it. It appears to be using the `baseUrl` returned by the streaming servers `/settings` instead of the users specified streaming server URL.
