### ISSUE TITLE
ERR_EMPTY_RESPONSE when running in local

### ISSUE THREAD

**Issue by vjtvalero** [Stremio/stremio-web#435]
I'm trying to run it in my local. It says:
![image](https://github.com/Stremio/stremio-web/assets/18051546/b0c186e7-b38e-4eac-aef4-6cccb36ecdd1)

Just installed the deps normally and run `npm start`

webpack also looked good:
![image](https://github.com/Stremio/stremio-web/assets/18051546/61d8fa1a-884b-4910-8b25-ae69a88d7c6a)

Thank you in advance.

**Comment by tymmesyde** [comment]
It should be `https://localhost:8080`
You can also click on the url in the console to open it in your browser

**Comment by vjtvalero** [comment]
> It should be `https://localhost:8080` You can also click on the url in the console to open it in your browser

For some reason, I assumed localhost won't work with https. Thank you.

Issue closed.
