### ISSUE TITLE
[Missing Feature] Mark as Watched

### ISSUE THREAD

**Issue by elpiel** [Stremio/stremio-web#446]
The Desktop feature marks either a Movie series or a Movie as watched.
This action should trigger an action to core `MarkAsWatched` and on desktop the menu item for this is located in your library:

![Screenshot from 2023-08-21 11-21-49](https://github.com/Stremio/stremio-web/assets/8925621/16014439-e811-48b3-a1ed-55a7e6b27c65)

![Screenshot from 2023-08-21 11-21-59](https://github.com/Stremio/stremio-web/assets/8925621/0c1cb8a3-d165-4a92-96be-8782242fa218)

**Comment by kKaskak** [comment]
Closing as this feature is alr implemented
