### ISSUE TITLE
[feature request] Add a 'Not Watched' section in Library

### ISSUE THREAD

**Issue by gabrielRibeir0** [Stremio/stremio-web#457]
I think it would be nice to have a Not Watched section, same as the existing Watched, but with the not watched movies/series, obviously.

**Comment by kKaskak** [comment]
Hello, this was added in the newest release. Happy watching!

<img width="964" alt="Screenshot 2024-03-28 at 21 49 03" src="https://github.com/Stremio/stremio-web/assets/117831817/c175584b-b2f5-403a-80c8-4c6210b495fd">
