### ISSUE TITLE
Cursor not hiding on Samsung TV Browser (TizenBrowser 4.2.11030)

### ISSUE THREAD

**Issue by mjerma** [Stremio/stremio-web#459]
When using Stremio web on Samsung TV (QN90A), cursor is active and never hides, even when using fullscreen. Another user posted about it on reddit recently so it's not exclusive to my unit. 

https://www.reddit.com/r/Stremio/comments/11f0m5w/hiding_cursor_using_stremio_with_samsung_tv_tizen/

**Comment by kKaskak** [comment]
Hi! There is an official app released for Samsung TV, you can check it out. This issue is no longer relevant.
