### ISSUE TITLE
Did stremio just revert to old UI??

### ISSUE THREAD

**Issue by socksprox** [Stremio/stremio-web#494]
If so, i think it’s a terrible thing and I would at least like a button to switch to the new (now old??) UI
![IMG_1457](https://github.com/Stremio/stremio-web/assets/36358673/6b236153-14ee-4ccc-b835-14c60e8296a6)
![IMG_1458](https://github.com/Stremio/stremio-web/assets/36358673/2c7fd2b8-5a0d-42fd-8e35-a84802ad51d4)

**Comment by elpiel** [comment]
Hello, Thank you for reporting the issue.
We had to apply some patches to the current version and by accident we used an older commit (before the actual redesign).

We've fixed this issue yesterday and you can again enjoy the latest design of stremio-web!
