### ISSUE TITLE
Filename not being provided to subtitle handler

### ISSUE THREAD

**Issue by daniel-lxs** [Stremio/stremio-web#519]
At this moment is not possible to get the file name of the media that is playing, making it very hard to search for the matching subtitle file only by imdb, this makes it really hard to match to the media and having to try one by one.

![image](https://github.com/Stremio/stremio-web/assets/57051444/8589e5b7-0545-4eb3-9998-e16b8716a26c)

**Comment by elpiel** [comment]
Hello @daniel-lxs ,
thank you for reporting this issue.
In `development` this issue has already been solved and addons requests include the filename as well.

Feel free to re-open the issue if you find any edge-cases

![image](https://github.com/Stremio/stremio-web/assets/8925621/a240b8a8-1953-4e00-8ed3-b13117a2ad14)
