### ISSUE TITLE
Add Nepali Language in interfaceLanguages.json for Translation

### ISSUE THREAD

**Issue by kooolarpan** [Stremio/stremio-web#543]
https://github.com/Stremio/stremio-web/blob/a2c10e5d14a94d1a7941218441cf6f8b176c6522/src/common/interfaceLanguages.json#L31

   ```
 {
        "name": "नेपाली",
        "codes": ["ne-NP", "ne"]
    }
```
I would like to contribute with the translation. But, Nepali language is not detected in the Stremio.

**Comment by tymmesyde** [comment]
You will need to create a PR to add a new file named `ne-NP.json` for this repo https://github.com/Stremio/stremio-translations
And export it in the index file https://github.com/Stremio/stremio-translations/blob/master/index.js
After that you can add your suggestion to stremio-web

**Comment by kooolarpan** [comment]
Thanks.
