### ISSUE TITLE
Feature: pause/play by pressing on video

### ISSUE THREAD

**Issue by arabas41323** [Stremio/stremio-web#553]
Please add so you could just press on video to pause/play video, because now you need to press button SPACE or press on Play/Pause button

**Comment by Iheuzio** [comment]
If you're using the `https://web.stremio.com/#/player/`, the feature is already supported. This feature does not need to be implemented

**Comment by arabas41323** [comment]
i mean for windows stremio, idk if i created issue it in right place

**Comment by TRtomasz** [comment]
this would change most basic behavior of stremio player, that users are already used to, so we will not implement this.
