### ISSUE TITLE
4k Streams Showing Blank Screen

### ISSUE THREAD

**Issue by MikeKaiser55** [Stremio/stremio-web#554]
Recently on Stremio Web any torrentio 4k stream i try to watch just plays a blank stream with audio working fine.
But the desktop version is working properly and all the 4k Streams are also working properly.

**Comment by kKaskak** [comment]
> Recently on Stremio Web any torrentio 4k stream i try to watch just plays a blank stream with audio working fine. But the desktop version is working properly and all the 4k Streams are also working properly.

Hi! Investigated the issue and on my end everything is working fine. Could you provide more details related to the issue? Chrome version, stremio-web version (might be old if you're using a PWA and didn't update it), and your device model. Thanks!

**Comment by MikeKaiser55** [comment]
Hi there! Thank you for replying. 
Chrome Version - 
![image](https://github.com/Stremio/stremio-web/assets/69754465/cf424cbd-8676-47f4-8fc5-31f987ed024c)
Stremio Web Version - 
![image](https://github.com/Stremio/stremio-web/assets/69754465/e00adf05-b451-4e46-a25e-d68ef9684ca4)
Device Model - Windows 10 Pro
Some Screenshots providing Proof - Using the same movie and selecting the first 4k Torrentio Stream
Stremio Web - 
![image](https://github.com/Stremio/stremio-web/assets/69754465/57992517-a762-45f3-b698-52a029fba891)
Stremio Dekstop - 
![image](https://github.com/Stremio/stremio-web/assets/69754465/8edfb469-9f7b-4485-9356-58564eb24ce3)
I have also asked my other friends who use stremio to check and they are having the same problem too.

**Comment by TRtomasz** [comment]
As a workaround you could go to the stremio settings and enable `Surround sound`

**Comment by MikeKaiser55** [comment]
Hi! Even after enabling it its still not working.
Edit - It also disables the embedded subtitles too which i just noticed.

**Comment by kKaskak** [comment]
> Hi! Even after enabling it its still not working. Edit - It also disables the embedded subtitles too which i just noticed.

Hi. We received more reports that this issue is happening on Windows specifically. The team is working on a fix. Thank you for your patience.

**Comment by MikeKaiser55** [comment]
No Problem! Glad I could help. Just update us when the fix gets implemented.

**Comment by MikeKaiser55** [comment]
Hi There! Any Updates to this?

**Comment by kKaskak** [comment]
Hi as of now the investigation is over, and the error has been found. Now the team is looking for a possible solution to this problem since this is only happening on the Windows version of chrome. (Chrome is falsly reporting hevc as unsupported, but it does support it.) I will update you as quickly as possible.

**Comment by kKaskak** [comment]
> Hi There! Any Updates to this?

Hi as of now the investigation is over, and the error has been found. Now the team is looking for a possible solution to this problem since this is only happening on the Windows version of chrome. (Chrome is falsly reporting hevc as unsupported, but it does support it.) I will update you as quickly as possible.

**Comment by MikeKaiser55** [comment]
Thats Great! Tysm for the update.

**Comment by DreadPirateTony** [comment]
Was there any fix for this? I'm assuming mine is the same problem because 4K is all black on my screen

**Comment by MikeKaiser55** [comment]
Hi! Its still not working in google chrome. But its working on Firefox so I am using that for now. Hope it somewhat solves your problem!
