### ISSUE TITLE
Cannot connect stremio web running on LG TV's web browser to stremio service running on Macbook Pro

### ISSUE THREAD

**Issue by duyhoan** [Stremio/stremio-web#564]
Hi guys,

I'm trying to find a way to use stremio web with stremio service for accessing stremio on LG TV web browser. Here is my setup:

- I download and run the stremio service on my Macbook Pro
- I observe the local IP address of my Macbook via Network setting in System Preferences: Network -> Wifi -> Details on connected wifi -> TCP/IP -> IP Address
- I open [web.stremio.com](https://web.stremio.com/) on LG TV's web browser, log in and go to Settings -> Streaming
- I modify the Url configuration there and set it to be like this: http://{my_Macbook_local_IP_address}:11470

However, it keeps indicating the Server Error, which means that it cannot connect to the stremio service that is running on my Macbook. I already ensured that both of my Macbook and LG TV is connecting to the same Wifi network. Which step I'm missing here? Or how can I adapt LG TV / my Macbook network setting / my router to make it work?

Further information about the system hardware:

- My Macbook Pro is running on MacOS ventura with Apple M2 chip
- My LG TV is LG C3 evo, 2023 model. WebOS version is 03.30 I believe.

**Comment by kubo6472** [comment]
Can you connect from another device? I bought a Chromecast 4 with Google TV just for stremio, and it's been kinda worth it. Today, things are unexpectedly slow. The navigation on web.stremio.com was pain to do.

**Comment by AZalshehri7** [comment]
I have the same issue on a windows machine host.

Tried TV and mobile both do not work, on host machine using 127.0.0.1 it works without any issues. So it seems it is not making it accessible to the whole network

**Comment by tsaridas** [comment]
I believe the issue is that stremio server needs to be in https if you try to connect from a player that uses https. try to either have the player setup locally (LAN) with http or setup server with https.

**Comment by jaruba** [comment]
Stremio is now available for LG TV in the app store: https://blog.stremio.com/stremio-is-now-available-on-lg-tvs-for-models-2020/

**Comment by AlvaroRojas** [comment]
Same issue here with a docker deployed in a server when trying to cast using stremio web.
