### ISSUE TITLE
Support for DTS-HD passthrough in ExoPlayer

### ISSUE THREAD

**Issue by Perza83** [Stremio/stremio-web#581]
The ExoPlayer is missing support for DTS-HD. Other formats like DD Atmos, True-HD etc. are working properly with a dedicated device (nvidia shield tv pro connected to an AVR). One solution is using 3rd party player ("Just (video) Player" for example) but user loses the ability to select subtitles from other addons in that player.

**Comment by TRtomasz** [comment]
We do not control features that are in the exoplayer. Also this is repository fro stremio-web
