### ISSUE TITLE
[Feature-Request] Add the option for "Not Watched" in the library #388

### ISSUE THREAD

**Issue by ensapra** [Stremio/stremio-web#582]
Currently, the library has the watched option, but it doesn't make sense that we cannot sort by unwatched too. Not only that, but it would be nice for those categories to remove the items that don't comply (on watched, remove the watched items, and on unwatched, remove the watched ones)

https://github.com/Stremio/stremio-features/issues/74
https://github.com/Stremio/stremio-features/issues/552
https://github.com/Stremio/stremio-shell/issues/388

**Comment by ensapra** [comment]
After hearing @jaruba comments, I propose this new idea:

# The idea
 - Have a new sort value called Not Watched. This one would work in reverse to the current By Times Watched (that should be renamed to Watched)

## Quality of Life to improve looks
- This sorting options, Not Watched and Watched will separate the library into two sections. The one on top is the selected sort, separated by a separator, and the rest of the items under it. If there are no items in the sorted selected a message should appear (No items to watch left) (No items watched)
- The items will move from Not Watched to Watched when:
	- A movie is fuly watched
	- A show has the latest available episode watched, and there are no new episodes (a new episode should already make the last episode watched not be the last episode available)
	- The item is marked as watched
- The item will move from Watched to Not Watched when:
	- A show has a new episode released
	- The item is marked as not watched
- The items in Watched will be sorted by latest watched item first
- The items in Not Watched will be sorted by newest episode first, if no new episodes, recently added to the library first

**Comment by jaruba** [comment]
I may be too tired to understand everything you are trying to explain, but i am pretty sure that over 90% of it is not based on my comments..

**Comment by ensapra** [comment]
It's based on the comment that adding an extra filter option could be seen as bad UX and that is preferred to add a new sorting option.
This request develops that option by adding some extra QoL features in addition to the new sorting type (Not watched)

**Comment by jaruba** [comment]
@ensapra you said "according to jaruba", ur comment is not according to me at all, i only outlined the issue

you need to be careful when stating my name as it can be confused with an official decided task, which it is not at this point

**Comment by ensapra** [comment]
Ah I see the confusion, let me modify the request to better reflect the situation then.

**Comment by kKaskak** [comment]
#610

**Comment by SJ1O** [comment]
It would be great if the not watched was sorted so the most recently added was at the start.
