### ISSUE TITLE
[BUG] Next video button plays the same file after 2 autoplays (if allowed to automatically choose the file)

### ISSUE THREAD

**Issue by Edwinsiddy1** [Stremio/stremio-web#590]
Only ever experience this on the web app. It will act as if it moved on to the next episode with the title changing, but the file it plays is the same file as before. 

**Here's a brief rundown of what happens:
Manually Slect Episode 3 -> Episode 3 playing -> I click next video -> Says episode 4 is playing (plays episode 4) -> click next video -> Says episode 5 is playing (plays episode 4) -> click next video -> Says episode 6 is playing (plays episode 4) ->etc.**

Seems it only happens if I click the next episode button and it automatically loads the next video (doesn't ask for a specific version of the file) If I back out of the video player and re-select the episode it works as normal, its only is when it auto plays.

Seems to happen on both ios and windows

**Comment by Unshortafleur** [comment]
I can confirm. Same behavior happening to me for a few days now.
Sometimes it just reload the same file that the one i just watched (at the timestamp that i was at when i clicked next) but with the next episode metadata. This also consider the next episode as watched.

**Comment by kKaskak** [comment]
- [x] https://github.com/Stremio/stremio-core/pull/664
