### ISSUE TITLE
[Feature-Request] Advanced library filter (directors, imdb rating, year, watched, personally liked, etc)

### ISSUE THREAD

**Issue by iplanwebsites** [Stremio/stremio-web#613]
With Stremio becoming a Spotify for cinema, we need better ways to look at our library.
Playlists, likes and rating would be feature on their own, but it's be very easy to implement simple list filters and a grid view. 
I'd be happy to help with the UI design if someone want to tackle this feature.

**Comment by kKaskak** [comment]
Hi! The newly launched version improves the library filtering / sorting a lot ✅. Thank you for using Stremio
<img width="887" alt="Screenshot 2024-03-28 at 21 06 35" src="https://github.com/Stremio/stremio-web/assets/117831817/7f28bd17-5597-40bd-bebc-484cdcf74ae8">

**Comment by iplanwebsites** [comment]
Looking good! 
That's definitely a step in the right direction. I still think a lot more could be done and would be happy to help improve that UI.  I think powerful library browsing tools will really be appreciated from cinema nerds.
