### ISSUE TITLE
White screen on lg webos browser

### ISSUE THREAD

**Issue by Sabream** [Stremio/stremio-web#626]
Hi all,
whenever i try to load https://web.stremio.com i get a white empty screen on my lg 55b7v.

Is there a workaround?

**Comment by kKaskak** [comment]
Hello your TV model seems to be from 2017, I believe we do not support Chrome versions older than 2019, so there is no way for you to use it on this TV (Chrome 65.0.3299.0 is used on it). Sorry for the inconvenience.
