### ISSUE TITLE
Unable to install Stremio from play store

### ISSUE THREAD

**Issue by vijayvcm** [Stremio/stremio-web#635]
Hello,

I am not sure if it's a feature or a bug. So, I just left that title alone.

I am from India. I am using the below TV.

Brand: Mi/Xiaomi
Model: Xiaomi MiTV-MOOQ0

I can sideload the app downloaded directly from the Stremio website but the same app is not showing to me on the Play Store. This is the message I am seeing.

I can watch movies and TV shows without any issues, and it works flawlessly. I am unsure why it shows it's unavailable for my device. 

Any solutions or suggestions would be helpful.

<img width="887" alt="image" src="https://github.com/Stremio/stremio-web/assets/11239522/6eee2bfb-f778-4076-bad0-e2ecf3457742">

<img width="880" alt="image" src="https://github.com/Stremio/stremio-web/assets/11239522/dcc5a638-219d-40d7-9eb0-09268aa16a3f">

**Comment by TRtomasz** [comment]
First of all this is wrong repository, this is repository for stremio web app.
Stremio app is not available in Play Store for India, you have to sideload it.
