### ISSUE TITLE
Add Samsung TV and LG TV in Stremio Website 

### ISSUE THREAD

**Issue by Kresbok** [Stremio/stremio-web#637]
When you go to Stremio web site and you see the description of devices available Samsung TV and LG TV are missing.

![Add Samsung TV and LG TV on Stremio website](https://github.com/Stremio/stremio-web/assets/121912374/bc1a1c19-5a2b-4db5-8cab-5651dd821d38)

Thank you guys!

**Comment by jaruba** [comment]
@alesinka why me? i'm sure @kKaskak can handle it if u give him the icons 🫣

**Comment by kKaskak** [comment]
I was going to do this right now

**Comment by alesinka** [comment]
> @alesinka why me? i'm sure @kKaskak can handle it if u give him the icons 🫣

Sorry, i didnt know that. I thought only you managed the website :)

**Comment by alesinka** [comment]
https://xd.adobe.com/view/55b54076-6b7a-48df-abdb-e62be6cc1790-00e6/specs/ here logos can be downloaded. @kKaskak  let me know if you need anything for this one.
