### ISSUE TITLE
Option to close the Sidebar

### ISSUE THREAD

**Issue by Aryadev19** [Stremio/stremio-web#639]
something like this.....
![Screenshot 2024-05-03 100939](https://github.com/Stremio/stremio-web/assets/94225310/0c6c2dce-a66c-49cb-854b-d0e99e27da81)

Add a button to toggle the sidebar so we can see the full backdrop image!

**Comment by kKaskak** [comment]
You will be able to see it when starting to watch the movie / series episode
https://github.com/Stremio/stremio-web/pull/642
