### ISSUE TITLE
stremio-web streaming not work on android

### ISSUE THREAD

**Issue by NeoLaner** [Stremio/stremio-web#653]
I recently installed the latest Android APK, but it appears that the probe request from the web app to the Stremio service is not functioning correctly. Despite testing with various torrent files, none of them worked.

![photo_2024-06-23_13-58-04](https://github.com/Stremio/stremio-web/assets/142805740/ae00ddc0-7b0d-4025-9a65-65e7266a971f)
![photo_2024-06-23_13-58-00](https://github.com/Stremio/stremio-web/assets/142805740/79bcc925-3c31-481c-a765-82e6e2c7e073)

tested in:
android 12,13
chrome latest

**Comment by TRtomasz** [comment]
there is no probe in streaming server on android
