### ISSUE TITLE
M1 Stremio Desktop App Dropdown Incorrect Styling

### ISSUE THREAD

**Issue by sircoderin** [Stremio/stremio-web#659]
I think there is an issue with the styling for the M1 Desktop version as it doesn't look like web. I attached down bellow for comparisson.
<img width="232" alt="Screenshot 2024-07-12 at 15 22 05" src="https://github.com/user-attachments/assets/08516e16-1fa9-4af5-bb02-33623193fa8c">
<img width="286" alt="Screenshot 2024-07-12 at 15 23 00" src="https://github.com/user-attachments/assets/87dd1d39-7a2b-4d8e-b9b6-6f12cae2c562">

**Comment by tymmesyde** [comment]
The desktop app looks like this because it uses the system drop downs instead of custom ones like in stremio-web
