### ISSUE TITLE
futurama series is mangled in Stremio

### ISSUE THREAD

**Issue by ghost** [Stremio/stremio-web#672]
I understand you're experiencing issues with the metadata and episode numbering for Futurama in Stremio, particularly from season 6 onward. This seems to be a complex problem involving multiple factors. Let me summarize the key points and offer some thoughts:

1. Metadata mismatch: The episode data in the app doesn't match up correctly with the actual episodes.

2. Third-party plugin interference: You suspect some third-party plugins might be causing issues.

3. Inconsistent season numbering: Futurama has different season numberings based on various release formats (broadcast order, production order, streaming order, etc.).

4. Stremio's chosen numbering system: It appears Stremio is using the streaming release order, but even then, there are problems with Season 6 and other missing episodes.

5. Torrent detection/labeling: There may be issues with how published torrents are detected or labeled within the system.

6. Audio track problems: You mentioned issues with only commentary tracks being available on the Samsung app.

Your suggestion about making the apps "knowledgeable" about different numbering formats is a good one. This approach, often called "scene mapping" or "episode mapping," can help reconcile different numbering systems. It would involve maintaining a database that maps episodes across different numbering schemes.

For a comprehensive fix, the Stremio developers might need to:

1. Review and potentially change their metadata source.
2. Implement a robust episode mapping system.
3. Improve torrent detection and labeling algorithms.
4. Investigate the audio track selection issue, especially on the Samsung app.
5. Consider allowing users to manually select which numbering system they prefer.

As a user, you've done a great job identifying and reporting these issues. The Wikipedia page you linked (https://en.wikipedia.org/wiki/List_of_Futurama_episodes) is indeed a good reference for the various numbering systems used for Futurama.

To help the developers address this, you might want to:

1. Report this issue through Stremio's official channels if you haven't already.
2. Provide specific examples of mismatched episodes.
3. Share the Wikipedia link as a reference for correct episode ordering.
4. Suggest the implementation of a flexible episode mapping system.

Remember, complex issues like this often take time to resolve, especially when they involve third-party data and multiple numbering systems. Your detailed feedback is valuable for improving the service for all users.

**Comment by kKaskak** [comment]
Hi. I refreshed the metadata for the Futurama series. It should be live in 24-48h.

**Comment by kKaskak** [comment]
https://www.imdb.com/title/tt0149460/episodes/?season=1 I think the episodes you see in stremio are consistent with the ones on imdb at least for me.

**Comment by kKaskak** [comment]
Hi, it's not possible for another add-on to interact with the Cinemeta add-on. The results I'm seeing match those on IMDb, and we don't support Wikipedia. It seems like the issue might be with either Wiki or IMDb that have messed up episodes. Can't do anything in this case. You can write to IMDb or Wiki if this is possible.

**Comment by ghost** [comment]
@jaruba Can you please add perspective how is this metadata and episodes not correlating correctly ?

**Comment by jaruba** [comment]
futurama episodes are a special case, the fact that they are mangled is because hulu decided to change the distribution order, there is no such thing as a "correct episode list", they are all correct because they all conform to a specific distribution order from a specific distributor

for futurama in particular we investigated the case, and the current episode list is the "most correct" for most cases, because u will find streams for the new episodes in season 12, but in season 9 (which is considered latest by hulu) you will find mangled streams for both new season (from hulu) and old season (from other distributors)

stremio cannot use wikipedia episode lists, it can use tmdb, tvdb or imdb episode lists

**Comment by kKaskak** [comment]
> futurama episodes are a special case, the fact that they are mangled is because hulu decided to change the distribution order, there is no such thing as a "correct episode list", they are all correct because they all conform to a specific distribution order from a specific distributor
> 
> for futurama in particular we investigated the case, and the current episode list is the "most correct" for most cases, because u will find streams for the new episodes in season 12, but in season 9 (which is considered latest by hulu) you will find mangled streams for both new season (from hulu) and old season (from other distributors)
> 
> stremio cannot use wikipedia episode lists, it can use tmdb, tvdb or imdb episode lists

Thanks for clearing this out. I wasn't aware that Futurama is a special case.
