### ISSUE TITLE
ubuntu 24.04 support

### ISSUE THREAD

**Issue by krasi-georgiev** [Stremio/stremio-web#673]
none of the mentioned installation methods work on ubunutu 24.04

Would you provide deb of appimage for ubuntu 24.04

**Comment by TRtomasz** [comment]
Please be more specific when reporting issue, also check if you opened it in the correct repository as this is repository for stremio-web app there is no appimage. Stremio-bugs is for reporting bugs.
If this is about stremio-shell there is flatpak https://flathub.org/apps/com.stremio.Stremio package
