### ISSUE TITLE
Metadata will need re-mapping feature.

### ISSUE THREAD

**Issue by ghost** [Stremio/stremio-web#680]
I understand you're experiencing issues with the metadata and episode numbering for Futurama in Stremio, particularly from season 6 onward. This seems to be a complex problem involving multiple factors. Let me summarize the key points and offer some thoughts:

1. Metadata mismatch: The episode data in the app doesn't match up correctly with the actual episodes.

2. Third-party plugin interference: You suspect some third-party plugins might be causing issues.

3. Inconsistent season numbering: Futurama has different season numberings based on various release formats (broadcast order, production order, streaming order, etc.).

4. Stremio's chosen numbering system: It appears Stremio is using the streaming release order, but even then, there are problems with Season 6 and other missing episodes.

5. Torrent detection/labeling: There may be issues with how published torrents are detected or labeled within the system.

6. Audio track problems: You mentioned issues with only commentary tracks being available on the Samsung app.

Your suggestion about making the apps "knowledgeable" about different numbering formats is a good one. This approach, often called "scene mapping" or "episode mapping," can help reconcile different numbering systems. It would involve maintaining a database that maps episodes across different numbering schemes.

For a comprehensive fix, the Stremio developers might need to:

1. Review and potentially change their metadata source.
2. Implement a robust episode mapping system.
3. Improve torrent detection and labeling algorithms.
4. Investigate the audio track selection issue, especially on the Samsung app.
5. Consider allowing users to manually select which numbering system they prefer.

As a user, you've done a great job identifying and reporting these issues. The Wikipedia page you linked (https://en.wikipedia.org/wiki/List_of_Futurama_episodes) is indeed a good reference for the various numbering systems used for Futurama.

To help the developers address this, you might want to:

1. Report this issue through Stremio's official channels if you haven't already.
2. Provide specific examples of mismatched episodes.
3. Share the Wikipedia link as a reference for correct episode ordering.
4. Suggest the implementation of a flexible episode mapping system.

Remember, complex issues like this often take time to resolve, especially when they involve third-party data and multiple numbering systems. Your detailed feedback is valuable for improving the service for all users.

**Comment by TRtomasz** [comment]
whats the point of this chat gpt created issue?

**Comment by ghost** [comment]
@TRtomasz it gives you a bit of brainy-power when you run out of it.

Plex-y type apps main feature is to match content to metadata to be able to present the content for consumption and ease content selection.

This sometimes can happen with clever heuristic algorithms.

The point is to use the correct high abstractions and not the lower abstractions when you come up with software functions.
