### ISSUE TITLE
"npm start" throws error

### ISSUE THREAD

**Issue by MuditAtrey** [Stremio/stremio-web#681]
<img width="716" alt="Screenshot 2024-09-15 at 9 50 34 AM" src="https://github.com/user-attachments/assets/272fc264-111d-4640-93a4-a99eaf0446d3">

I downloaded the latest release, opened a terminal window on it, ran "npm install" and "npm audit fix" which now shows 0 vulnerabilities, after this I tried to do "npm start" which gave the errors above

I am sorry if this is a dumb thing that everyone is able to fix, I am new to this

**Comment by MuditAtrey** [comment]
This is the log mentioned in the image above



0 verbose cli /usr/local/bin/node /usr/local/bin/npm
1 info using npm@10.2.3
2 info using node@v21.2.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:project Completed in 2ms
10 timing config:load:file:/Users/muditatrey/.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:setEnvs Completed in 1ms
15 timing config:load Completed in 9ms
16 timing npm:load:configload Completed in 9ms
17 timing config:load:flatten Completed in 3ms
18 timing npm:load:mkdirpcache Completed in 5ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm start
21 verbose argv "start"
22 timing npm:load:setTitle Completed in 33ms
23 timing npm:load:display Completed in 4ms
24 verbose logfile logs-max:10 dir:/Users/muditatrey/.npm/_logs/2024-09-15T04_20_17_519Z-
25 verbose logfile /Users/muditatrey/.npm/_logs/2024-09-15T04_20_17_519Z-debug-0.log
26 timing npm:load:logFile Completed in 14ms
27 timing npm:load:timers Completed in 0ms
28 timing npm:load:configScope Completed in 0ms
29 timing npm:load Completed in 96ms
30 silly logfile start cleaning logs, removing 1 files
31 silly logfile done cleaning log files
32 timing command:run-script Completed in 13ms
33 timing command:start Completed in 19ms
34 verbose stack Error: Missing script: "start"
34 verbose stack
34 verbose stack Did you mean one of these?
34 verbose stack     npm star # Mark your favorite packages
34 verbose stack     npm stars # View packages marked as favorites
34 verbose stack
34 verbose stack To see a list of scripts, run:
34 verbose stack   npm run
34 verbose stack     at RunScript.run (/usr/local/lib/node_modules/npm/lib/commands/run-script.js:94:13)
34 verbose stack     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli-entry.js:61:5)
35 verbose cwd /Users/muditatrey/Downloads/build 2
36 verbose Darwin 23.6.0
37 verbose node v21.2.0
38 verbose npm  v10.2.3
39 error Missing script: "start"
39 error
39 error Did you mean one of these?
39 error     npm star # Mark your favorite packages
39 error     npm stars # View packages marked as favorites
39 error
39 error To see a list of scripts, run:
39 error   npm run
40 verbose exit 1
41 timing npm Completed in 165ms
42 verbose code 1
43 error A complete log of this run can be found in: /Users/muditatrey/.npm/_logs/2024-09-15T04_20_17_519Z-debug-0.log

**Comment by MuditAtrey** [comment]
I am adding this here, it might be related, 
I tried turning on https mode on the stremio app on my mac, and it gave me 

"https certificate request failed"

so to investigate I started the application through terminal, and when I try to start the https mode, it gives me this statement
 
js: HTTPS error [object Response]
js: Access to fetch at 'https://9546dcbb7c1c-stremio-fmovies.baby-beamup.club/catalog/movie/top.json' from origin 'https://app.strem.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
js: Access to fetch at 'https://twitch.baby-supernode.xyz/catalog/tv/twitch_catalog.json' from origin 'https://app.strem.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.


I am not able to find a way to disable CORS or set NO_CORS to 1 for the stremio app
I did set NO_CORS to 1 on the docker stremio container, but to no avail, I still can't play torrents from a different device on the same network using stremio web while the server is running

**Comment by tymmesyde** [comment]
Hi, if you mean that you downloaded the `stremio-web.zip` file from the release, it contains build files so you can't use `npm start`. You need an web server to serve the files
If you want to get the code, you need to clone this repo or download the `Source code` zip from the release
