### ISSUE TITLE
Video is not supported and CORS

### ISSUE THREAD

**Issue by asaddon** [Stremio/stremio-web#706]
Hello, Im getiing this error on every video I'm trying to play via web.strem.io, everything works fine on app.strem.io using the same server URL but it's UI is not mobile optimized ( Using on iOS) , please let me know how to fix it.

![Screenshot 2024-10-08 at 10 07 57 PM](https://github.com/user-attachments/assets/7d409b37-9b83-4be0-ade0-e4cbc9d1736f)

**Comment by kKaskak** [comment]
Hello, this error means you are just not connected to the server. Use [web.stremio.com](https://web.stremio.com) instead. While testing locally make sure to reload the page to see the mobile UI while resizing (same in production). I tested locally with the server running from the app and while being on `web.strem.io` domain. Everything seems to be working correctly.
