### ISSUE TITLE
Android is being treated as "visionos" in external player dropdown

### ISSUE THREAD

**Issue by zunichky** [Stremio/stremio-web#708]
When on Android, going into settings and selecting an external player, the settings seem to be showing all of the "visionos" settings instead of android options. Options shown:
VLC
Outplayer
Moonplayer (VisionOS)
M3U Playlist

Expected options:
EXTERNAL_PLAYER_ALLOW_CHOOSING
VLC
MX Player
Just Player
M3U Playlist

Tested on Android Automotive OS hardware and a android pixel VM.

**Comment by TRtomasz** [comment]
Please go to https://www.whatismybrowser.com/detect/what-is-my-user-agent/ and send us your user agent.

**Comment by zunichky** [comment]
Mozilla/5.0 (Android 13; Mobile; rv:109.0) Gecko/110.0 Firefox/110.0
I'm testing on the production web.streamio.com (not self hosting). As of writing this, looks to be 5.0.0-beta.12

**Comment by TRtomasz** [comment]
and this is result from the browser used in your car system?

**Comment by zunichky** [comment]
That was from a VM. This is from my car system
<img width="340" alt="image" src="https://github.com/user-attachments/assets/1edd403d-c93c-44cf-940d-17bb8317e7f7">

**Comment by TRtomasz** [comment]
@zunichky  please try this version https://stremio.github.io/stremio-web/development/

**Comment by zunichky** [comment]
It works as expected with that URL. Sorry about that, didn't realize there was a release candidate version out there.
