### ISSUE TITLE
Sound stops working after connecting & disconnecting output devices

### ISSUE THREAD

**Issue by ptfpinho23** [Stremio/stremio-web#716]
I've noticed that whenever I plug-in my headphones & WIN changes my default output device & then I try to switch back to the default output device (in this case - TV speakers) the sound stops working. 

**Platform**

WIndows 11 23H2

**Replication Steps**

1. Start a stream through `stremio` 
2. Verify that sound is working correctly through your selected output device
3. Plug-in a secondary output device - e.g - headphones or external speakers & configure those as your output device
4. Verify that sound is working correctly through that secondary output
5. Unplug/Switch off this secondary output device - main output device (e.g laptop speakers) should now be selected (default WIN behaviour)
6. Verify that sound does not work anymore - can only get it working again through restarting `stremio`

I'm guessing there's something wrong with the output device selection when there are potentially multiple output devices & a switch happens on the OS level.

**Comment by kKaskak** [comment]
Hi! Is this happening while using the web app or the desktop app? Just want to make sure this is about the web app. Please share the domain you use as well. Thanks

**Comment by ptfpinho23** [comment]
You're completely right - my bad. This is indeed happening on the desktop app. 
I'll close this issue & re-open it in the right place - https://github.com/Stremio/stremio-shell/issues/419 

Cheers
