### ISSUE TITLE
[Bug]: stremio iphone browser doesn't go full screen

### ISSUE THREAD

**Issue by tsaridas** [Stremio/stremio-web#768]
![Screenshot 2024-12-23 at 13 06 18](https://github.com/user-attachments/assets/f0754108-e095-46ab-bf40-53736c65f5fe)
### Stremio-Web Version

/development branch

### Browser

Safari

### Platform / Device type

iOS Web latest updates installed

### What Happened?

I try to play a movie from stremio web through a browser in safari and full screen doesn't work

### Logs

```shell
TypeError: document.documentElement.requestFullscreen is not a function. (In 'document.documentElement.requestFullscreen()', 'document.documentElement.requestFullscreen' is undefined)
```

### Notes

I tried different browsers and the behaviour is the same

### Code of Conduct

- [X] I agree

**Comment by xrazis** [comment]
[As far as I know](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen), Safari has partial support (ipad only) for the Fullscreen API.

**Comment by kKaskak** [comment]
Hello, thank you for opening this issue. Yes that's true that Safari on iPhone does not support `reqeustFullscreen()`. In the meanwhile you can add web.stremio.com to your homepage as a PWA and you will get a fullscreen experience.

<img src="https://github.com/user-attachments/assets/ee35e7b0-1821-4099-bec3-970285d95a19" alt="Image description" height="300px">
