### ISSUE TITLE
chromecast player implementation based on the Chrome cast API

### ISSUE THREAD

**Issue by Ivshti** [Stremio/stremio-web#91]
https://developers.google.com/cast/docs/reference/chrome/

basically create `services/players/chromecast`

related to https://github.com/Stremio/stremio-web/issues/4 - in other words, should be done after this

this also allows dropping all casting (DLNA, chromecast) from the stremio-server, making it much simpler and more reliable; so related to this: https://github.com/Stremio/stremio-server/issues/11

This will only be used in the browser. In the shell, we don't have access to the chrome cast API, so we will use a different solution

**Comment by nklhtv** [comment]
Done
