### ISSUE TITLE
[ux] better icon for audio track 

### ISSUE THREAD

**Issue by Ivshti** [Stremio/stremio-web#99]
we need a more recognizable icon for the audio track selection, "DUB" is not very user friendly

here's an example, although we might be able to do it better (e.g. megaphone icon or something)

![amazon](https://user-images.githubusercontent.com/1247629/52564725-8c9c0b00-2e0d-11e9-93a7-e54e9edd6a52.png)

**Comment by nklhtv** [comment]
audio tracks will be shown in the subtitles menu
